// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CropMonitoringService.proto

package smartagriculture;

public final class CropMonitoringServiceOuterClass {
  private CropMonitoringServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CropIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smartagriculture.CropId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code smartagriculture.CropId}
   */
  public  static final class CropId extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smartagriculture.CropId)
      CropIdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CropId.newBuilder() to construct.
    private CropId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CropId() {
      id_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CropId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartagriculture.CropMonitoringServiceOuterClass.internal_static_smartagriculture_CropId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartagriculture.CropMonitoringServiceOuterClass.internal_static_smartagriculture_CropId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartagriculture.CropMonitoringServiceOuterClass.CropId.class, smartagriculture.CropMonitoringServiceOuterClass.CropId.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smartagriculture.CropMonitoringServiceOuterClass.CropId)) {
        return super.equals(obj);
      }
      smartagriculture.CropMonitoringServiceOuterClass.CropId other = (smartagriculture.CropMonitoringServiceOuterClass.CropId) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smartagriculture.CropMonitoringServiceOuterClass.CropId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smartagriculture.CropMonitoringServiceOuterClass.CropId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code smartagriculture.CropId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smartagriculture.CropId)
        smartagriculture.CropMonitoringServiceOuterClass.CropIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartagriculture.CropMonitoringServiceOuterClass.internal_static_smartagriculture_CropId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartagriculture.CropMonitoringServiceOuterClass.internal_static_smartagriculture_CropId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smartagriculture.CropMonitoringServiceOuterClass.CropId.class, smartagriculture.CropMonitoringServiceOuterClass.CropId.Builder.class);
      }

      // Construct using smartagriculture.CropMonitoringServiceOuterClass.CropId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartagriculture.CropMonitoringServiceOuterClass.internal_static_smartagriculture_CropId_descriptor;
      }

      @java.lang.Override
      public smartagriculture.CropMonitoringServiceOuterClass.CropId getDefaultInstanceForType() {
        return smartagriculture.CropMonitoringServiceOuterClass.CropId.getDefaultInstance();
      }

      @java.lang.Override
      public smartagriculture.CropMonitoringServiceOuterClass.CropId build() {
        smartagriculture.CropMonitoringServiceOuterClass.CropId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smartagriculture.CropMonitoringServiceOuterClass.CropId buildPartial() {
        smartagriculture.CropMonitoringServiceOuterClass.CropId result = new smartagriculture.CropMonitoringServiceOuterClass.CropId(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartagriculture.CropMonitoringServiceOuterClass.CropId) {
          return mergeFrom((smartagriculture.CropMonitoringServiceOuterClass.CropId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smartagriculture.CropMonitoringServiceOuterClass.CropId other) {
        if (other == smartagriculture.CropMonitoringServiceOuterClass.CropId.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smartagriculture.CropMonitoringServiceOuterClass.CropId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smartagriculture.CropMonitoringServiceOuterClass.CropId) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smartagriculture.CropId)
    }

    // @@protoc_insertion_point(class_scope:smartagriculture.CropId)
    private static final smartagriculture.CropMonitoringServiceOuterClass.CropId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smartagriculture.CropMonitoringServiceOuterClass.CropId();
    }

    public static smartagriculture.CropMonitoringServiceOuterClass.CropId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CropId>
        PARSER = new com.google.protobuf.AbstractParser<CropId>() {
      @java.lang.Override
      public CropId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CropId(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CropId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CropId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smartagriculture.CropMonitoringServiceOuterClass.CropId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CropStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smartagriculture.CropStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string status = 2;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 2;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>string growthStage = 3;</code>
     */
    java.lang.String getGrowthStage();
    /**
     * <code>string growthStage = 3;</code>
     */
    com.google.protobuf.ByteString
        getGrowthStageBytes();

    /**
     * <code>repeated string pests = 4;</code>
     */
    java.util.List<java.lang.String>
        getPestsList();
    /**
     * <code>repeated string pests = 4;</code>
     */
    int getPestsCount();
    /**
     * <code>repeated string pests = 4;</code>
     */
    java.lang.String getPests(int index);
    /**
     * <code>repeated string pests = 4;</code>
     */
    com.google.protobuf.ByteString
        getPestsBytes(int index);

    /**
     * <code>float moistureLevel = 5;</code>
     */
    float getMoistureLevel();
  }
  /**
   * Protobuf type {@code smartagriculture.CropStatus}
   */
  public  static final class CropStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smartagriculture.CropStatus)
      CropStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CropStatus.newBuilder() to construct.
    private CropStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CropStatus() {
      id_ = 0;
      status_ = "";
      growthStage_ = "";
      pests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      moistureLevel_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CropStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              growthStage_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                pests_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              pests_.add(s);
              break;
            }
            case 45: {

              moistureLevel_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          pests_ = pests_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartagriculture.CropMonitoringServiceOuterClass.internal_static_smartagriculture_CropStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartagriculture.CropMonitoringServiceOuterClass.internal_static_smartagriculture_CropStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartagriculture.CropMonitoringServiceOuterClass.CropStatus.class, smartagriculture.CropMonitoringServiceOuterClass.CropStatus.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private volatile java.lang.Object status_;
    /**
     * <code>string status = 2;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROWTHSTAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object growthStage_;
    /**
     * <code>string growthStage = 3;</code>
     */
    public java.lang.String getGrowthStage() {
      java.lang.Object ref = growthStage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        growthStage_ = s;
        return s;
      }
    }
    /**
     * <code>string growthStage = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGrowthStageBytes() {
      java.lang.Object ref = growthStage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        growthStage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PESTS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList pests_;
    /**
     * <code>repeated string pests = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPestsList() {
      return pests_;
    }
    /**
     * <code>repeated string pests = 4;</code>
     */
    public int getPestsCount() {
      return pests_.size();
    }
    /**
     * <code>repeated string pests = 4;</code>
     */
    public java.lang.String getPests(int index) {
      return pests_.get(index);
    }
    /**
     * <code>repeated string pests = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPestsBytes(int index) {
      return pests_.getByteString(index);
    }

    public static final int MOISTURELEVEL_FIELD_NUMBER = 5;
    private float moistureLevel_;
    /**
     * <code>float moistureLevel = 5;</code>
     */
    public float getMoistureLevel() {
      return moistureLevel_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, status_);
      }
      if (!getGrowthStageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, growthStage_);
      }
      for (int i = 0; i < pests_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, pests_.getRaw(i));
      }
      if (moistureLevel_ != 0F) {
        output.writeFloat(5, moistureLevel_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, status_);
      }
      if (!getGrowthStageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, growthStage_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < pests_.size(); i++) {
          dataSize += computeStringSizeNoTag(pests_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPestsList().size();
      }
      if (moistureLevel_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, moistureLevel_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smartagriculture.CropMonitoringServiceOuterClass.CropStatus)) {
        return super.equals(obj);
      }
      smartagriculture.CropMonitoringServiceOuterClass.CropStatus other = (smartagriculture.CropMonitoringServiceOuterClass.CropStatus) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getStatus()
          .equals(other.getStatus());
      result = result && getGrowthStage()
          .equals(other.getGrowthStage());
      result = result && getPestsList()
          .equals(other.getPestsList());
      result = result && (
          java.lang.Float.floatToIntBits(getMoistureLevel())
          == java.lang.Float.floatToIntBits(
              other.getMoistureLevel()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + GROWTHSTAGE_FIELD_NUMBER;
      hash = (53 * hash) + getGrowthStage().hashCode();
      if (getPestsCount() > 0) {
        hash = (37 * hash) + PESTS_FIELD_NUMBER;
        hash = (53 * hash) + getPestsList().hashCode();
      }
      hash = (37 * hash) + MOISTURELEVEL_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMoistureLevel());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smartagriculture.CropMonitoringServiceOuterClass.CropStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code smartagriculture.CropStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smartagriculture.CropStatus)
        smartagriculture.CropMonitoringServiceOuterClass.CropStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartagriculture.CropMonitoringServiceOuterClass.internal_static_smartagriculture_CropStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartagriculture.CropMonitoringServiceOuterClass.internal_static_smartagriculture_CropStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smartagriculture.CropMonitoringServiceOuterClass.CropStatus.class, smartagriculture.CropMonitoringServiceOuterClass.CropStatus.Builder.class);
      }

      // Construct using smartagriculture.CropMonitoringServiceOuterClass.CropStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        status_ = "";

        growthStage_ = "";

        pests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        moistureLevel_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartagriculture.CropMonitoringServiceOuterClass.internal_static_smartagriculture_CropStatus_descriptor;
      }

      @java.lang.Override
      public smartagriculture.CropMonitoringServiceOuterClass.CropStatus getDefaultInstanceForType() {
        return smartagriculture.CropMonitoringServiceOuterClass.CropStatus.getDefaultInstance();
      }

      @java.lang.Override
      public smartagriculture.CropMonitoringServiceOuterClass.CropStatus build() {
        smartagriculture.CropMonitoringServiceOuterClass.CropStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smartagriculture.CropMonitoringServiceOuterClass.CropStatus buildPartial() {
        smartagriculture.CropMonitoringServiceOuterClass.CropStatus result = new smartagriculture.CropMonitoringServiceOuterClass.CropStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.status_ = status_;
        result.growthStage_ = growthStage_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          pests_ = pests_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.pests_ = pests_;
        result.moistureLevel_ = moistureLevel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartagriculture.CropMonitoringServiceOuterClass.CropStatus) {
          return mergeFrom((smartagriculture.CropMonitoringServiceOuterClass.CropStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smartagriculture.CropMonitoringServiceOuterClass.CropStatus other) {
        if (other == smartagriculture.CropMonitoringServiceOuterClass.CropStatus.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        if (!other.getGrowthStage().isEmpty()) {
          growthStage_ = other.growthStage_;
          onChanged();
        }
        if (!other.pests_.isEmpty()) {
          if (pests_.isEmpty()) {
            pests_ = other.pests_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePestsIsMutable();
            pests_.addAll(other.pests_);
          }
          onChanged();
        }
        if (other.getMoistureLevel() != 0F) {
          setMoistureLevel(other.getMoistureLevel());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smartagriculture.CropMonitoringServiceOuterClass.CropStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smartagriculture.CropMonitoringServiceOuterClass.CropStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 2;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 2;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 2;</code>
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string status = 2;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object growthStage_ = "";
      /**
       * <code>string growthStage = 3;</code>
       */
      public java.lang.String getGrowthStage() {
        java.lang.Object ref = growthStage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          growthStage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string growthStage = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGrowthStageBytes() {
        java.lang.Object ref = growthStage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          growthStage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string growthStage = 3;</code>
       */
      public Builder setGrowthStage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        growthStage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string growthStage = 3;</code>
       */
      public Builder clearGrowthStage() {
        
        growthStage_ = getDefaultInstance().getGrowthStage();
        onChanged();
        return this;
      }
      /**
       * <code>string growthStage = 3;</code>
       */
      public Builder setGrowthStageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        growthStage_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList pests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePestsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          pests_ = new com.google.protobuf.LazyStringArrayList(pests_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string pests = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPestsList() {
        return pests_.getUnmodifiableView();
      }
      /**
       * <code>repeated string pests = 4;</code>
       */
      public int getPestsCount() {
        return pests_.size();
      }
      /**
       * <code>repeated string pests = 4;</code>
       */
      public java.lang.String getPests(int index) {
        return pests_.get(index);
      }
      /**
       * <code>repeated string pests = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPestsBytes(int index) {
        return pests_.getByteString(index);
      }
      /**
       * <code>repeated string pests = 4;</code>
       */
      public Builder setPests(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePestsIsMutable();
        pests_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pests = 4;</code>
       */
      public Builder addPests(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePestsIsMutable();
        pests_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pests = 4;</code>
       */
      public Builder addAllPests(
          java.lang.Iterable<java.lang.String> values) {
        ensurePestsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pests_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pests = 4;</code>
       */
      public Builder clearPests() {
        pests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pests = 4;</code>
       */
      public Builder addPestsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePestsIsMutable();
        pests_.add(value);
        onChanged();
        return this;
      }

      private float moistureLevel_ ;
      /**
       * <code>float moistureLevel = 5;</code>
       */
      public float getMoistureLevel() {
        return moistureLevel_;
      }
      /**
       * <code>float moistureLevel = 5;</code>
       */
      public Builder setMoistureLevel(float value) {
        
        moistureLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float moistureLevel = 5;</code>
       */
      public Builder clearMoistureLevel() {
        
        moistureLevel_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smartagriculture.CropStatus)
    }

    // @@protoc_insertion_point(class_scope:smartagriculture.CropStatus)
    private static final smartagriculture.CropMonitoringServiceOuterClass.CropStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smartagriculture.CropMonitoringServiceOuterClass.CropStatus();
    }

    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CropStatus>
        PARSER = new com.google.protobuf.AbstractParser<CropStatus>() {
      @java.lang.Override
      public CropStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CropStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CropStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CropStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smartagriculture.CropMonitoringServiceOuterClass.CropStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CropStatusListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smartagriculture.CropStatusList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
     */
    java.util.List<smartagriculture.CropMonitoringServiceOuterClass.CropStatus> 
        getCropStatusListList();
    /**
     * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
     */
    smartagriculture.CropMonitoringServiceOuterClass.CropStatus getCropStatusList(int index);
    /**
     * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
     */
    int getCropStatusListCount();
    /**
     * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
     */
    java.util.List<? extends smartagriculture.CropMonitoringServiceOuterClass.CropStatusOrBuilder> 
        getCropStatusListOrBuilderList();
    /**
     * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
     */
    smartagriculture.CropMonitoringServiceOuterClass.CropStatusOrBuilder getCropStatusListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code smartagriculture.CropStatusList}
   */
  public  static final class CropStatusList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smartagriculture.CropStatusList)
      CropStatusListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CropStatusList.newBuilder() to construct.
    private CropStatusList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CropStatusList() {
      cropStatusList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CropStatusList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                cropStatusList_ = new java.util.ArrayList<smartagriculture.CropMonitoringServiceOuterClass.CropStatus>();
                mutable_bitField0_ |= 0x00000001;
              }
              cropStatusList_.add(
                  input.readMessage(smartagriculture.CropMonitoringServiceOuterClass.CropStatus.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          cropStatusList_ = java.util.Collections.unmodifiableList(cropStatusList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartagriculture.CropMonitoringServiceOuterClass.internal_static_smartagriculture_CropStatusList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartagriculture.CropMonitoringServiceOuterClass.internal_static_smartagriculture_CropStatusList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartagriculture.CropMonitoringServiceOuterClass.CropStatusList.class, smartagriculture.CropMonitoringServiceOuterClass.CropStatusList.Builder.class);
    }

    public static final int CROPSTATUSLIST_FIELD_NUMBER = 1;
    private java.util.List<smartagriculture.CropMonitoringServiceOuterClass.CropStatus> cropStatusList_;
    /**
     * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
     */
    public java.util.List<smartagriculture.CropMonitoringServiceOuterClass.CropStatus> getCropStatusListList() {
      return cropStatusList_;
    }
    /**
     * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
     */
    public java.util.List<? extends smartagriculture.CropMonitoringServiceOuterClass.CropStatusOrBuilder> 
        getCropStatusListOrBuilderList() {
      return cropStatusList_;
    }
    /**
     * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
     */
    public int getCropStatusListCount() {
      return cropStatusList_.size();
    }
    /**
     * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
     */
    public smartagriculture.CropMonitoringServiceOuterClass.CropStatus getCropStatusList(int index) {
      return cropStatusList_.get(index);
    }
    /**
     * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
     */
    public smartagriculture.CropMonitoringServiceOuterClass.CropStatusOrBuilder getCropStatusListOrBuilder(
        int index) {
      return cropStatusList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < cropStatusList_.size(); i++) {
        output.writeMessage(1, cropStatusList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < cropStatusList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, cropStatusList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smartagriculture.CropMonitoringServiceOuterClass.CropStatusList)) {
        return super.equals(obj);
      }
      smartagriculture.CropMonitoringServiceOuterClass.CropStatusList other = (smartagriculture.CropMonitoringServiceOuterClass.CropStatusList) obj;

      boolean result = true;
      result = result && getCropStatusListList()
          .equals(other.getCropStatusListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCropStatusListCount() > 0) {
        hash = (37 * hash) + CROPSTATUSLIST_FIELD_NUMBER;
        hash = (53 * hash) + getCropStatusListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatusList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatusList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatusList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatusList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatusList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatusList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatusList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatusList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatusList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatusList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatusList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatusList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smartagriculture.CropMonitoringServiceOuterClass.CropStatusList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code smartagriculture.CropStatusList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smartagriculture.CropStatusList)
        smartagriculture.CropMonitoringServiceOuterClass.CropStatusListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartagriculture.CropMonitoringServiceOuterClass.internal_static_smartagriculture_CropStatusList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartagriculture.CropMonitoringServiceOuterClass.internal_static_smartagriculture_CropStatusList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smartagriculture.CropMonitoringServiceOuterClass.CropStatusList.class, smartagriculture.CropMonitoringServiceOuterClass.CropStatusList.Builder.class);
      }

      // Construct using smartagriculture.CropMonitoringServiceOuterClass.CropStatusList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCropStatusListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (cropStatusListBuilder_ == null) {
          cropStatusList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          cropStatusListBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartagriculture.CropMonitoringServiceOuterClass.internal_static_smartagriculture_CropStatusList_descriptor;
      }

      @java.lang.Override
      public smartagriculture.CropMonitoringServiceOuterClass.CropStatusList getDefaultInstanceForType() {
        return smartagriculture.CropMonitoringServiceOuterClass.CropStatusList.getDefaultInstance();
      }

      @java.lang.Override
      public smartagriculture.CropMonitoringServiceOuterClass.CropStatusList build() {
        smartagriculture.CropMonitoringServiceOuterClass.CropStatusList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smartagriculture.CropMonitoringServiceOuterClass.CropStatusList buildPartial() {
        smartagriculture.CropMonitoringServiceOuterClass.CropStatusList result = new smartagriculture.CropMonitoringServiceOuterClass.CropStatusList(this);
        int from_bitField0_ = bitField0_;
        if (cropStatusListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            cropStatusList_ = java.util.Collections.unmodifiableList(cropStatusList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.cropStatusList_ = cropStatusList_;
        } else {
          result.cropStatusList_ = cropStatusListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartagriculture.CropMonitoringServiceOuterClass.CropStatusList) {
          return mergeFrom((smartagriculture.CropMonitoringServiceOuterClass.CropStatusList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smartagriculture.CropMonitoringServiceOuterClass.CropStatusList other) {
        if (other == smartagriculture.CropMonitoringServiceOuterClass.CropStatusList.getDefaultInstance()) return this;
        if (cropStatusListBuilder_ == null) {
          if (!other.cropStatusList_.isEmpty()) {
            if (cropStatusList_.isEmpty()) {
              cropStatusList_ = other.cropStatusList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCropStatusListIsMutable();
              cropStatusList_.addAll(other.cropStatusList_);
            }
            onChanged();
          }
        } else {
          if (!other.cropStatusList_.isEmpty()) {
            if (cropStatusListBuilder_.isEmpty()) {
              cropStatusListBuilder_.dispose();
              cropStatusListBuilder_ = null;
              cropStatusList_ = other.cropStatusList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              cropStatusListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCropStatusListFieldBuilder() : null;
            } else {
              cropStatusListBuilder_.addAllMessages(other.cropStatusList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smartagriculture.CropMonitoringServiceOuterClass.CropStatusList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smartagriculture.CropMonitoringServiceOuterClass.CropStatusList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<smartagriculture.CropMonitoringServiceOuterClass.CropStatus> cropStatusList_ =
        java.util.Collections.emptyList();
      private void ensureCropStatusListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          cropStatusList_ = new java.util.ArrayList<smartagriculture.CropMonitoringServiceOuterClass.CropStatus>(cropStatusList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          smartagriculture.CropMonitoringServiceOuterClass.CropStatus, smartagriculture.CropMonitoringServiceOuterClass.CropStatus.Builder, smartagriculture.CropMonitoringServiceOuterClass.CropStatusOrBuilder> cropStatusListBuilder_;

      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public java.util.List<smartagriculture.CropMonitoringServiceOuterClass.CropStatus> getCropStatusListList() {
        if (cropStatusListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cropStatusList_);
        } else {
          return cropStatusListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public int getCropStatusListCount() {
        if (cropStatusListBuilder_ == null) {
          return cropStatusList_.size();
        } else {
          return cropStatusListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public smartagriculture.CropMonitoringServiceOuterClass.CropStatus getCropStatusList(int index) {
        if (cropStatusListBuilder_ == null) {
          return cropStatusList_.get(index);
        } else {
          return cropStatusListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public Builder setCropStatusList(
          int index, smartagriculture.CropMonitoringServiceOuterClass.CropStatus value) {
        if (cropStatusListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCropStatusListIsMutable();
          cropStatusList_.set(index, value);
          onChanged();
        } else {
          cropStatusListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public Builder setCropStatusList(
          int index, smartagriculture.CropMonitoringServiceOuterClass.CropStatus.Builder builderForValue) {
        if (cropStatusListBuilder_ == null) {
          ensureCropStatusListIsMutable();
          cropStatusList_.set(index, builderForValue.build());
          onChanged();
        } else {
          cropStatusListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public Builder addCropStatusList(smartagriculture.CropMonitoringServiceOuterClass.CropStatus value) {
        if (cropStatusListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCropStatusListIsMutable();
          cropStatusList_.add(value);
          onChanged();
        } else {
          cropStatusListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public Builder addCropStatusList(
          int index, smartagriculture.CropMonitoringServiceOuterClass.CropStatus value) {
        if (cropStatusListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCropStatusListIsMutable();
          cropStatusList_.add(index, value);
          onChanged();
        } else {
          cropStatusListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public Builder addCropStatusList(
          smartagriculture.CropMonitoringServiceOuterClass.CropStatus.Builder builderForValue) {
        if (cropStatusListBuilder_ == null) {
          ensureCropStatusListIsMutable();
          cropStatusList_.add(builderForValue.build());
          onChanged();
        } else {
          cropStatusListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public Builder addCropStatusList(
          int index, smartagriculture.CropMonitoringServiceOuterClass.CropStatus.Builder builderForValue) {
        if (cropStatusListBuilder_ == null) {
          ensureCropStatusListIsMutable();
          cropStatusList_.add(index, builderForValue.build());
          onChanged();
        } else {
          cropStatusListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public Builder addAllCropStatusList(
          java.lang.Iterable<? extends smartagriculture.CropMonitoringServiceOuterClass.CropStatus> values) {
        if (cropStatusListBuilder_ == null) {
          ensureCropStatusListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cropStatusList_);
          onChanged();
        } else {
          cropStatusListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public Builder clearCropStatusList() {
        if (cropStatusListBuilder_ == null) {
          cropStatusList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          cropStatusListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public Builder removeCropStatusList(int index) {
        if (cropStatusListBuilder_ == null) {
          ensureCropStatusListIsMutable();
          cropStatusList_.remove(index);
          onChanged();
        } else {
          cropStatusListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public smartagriculture.CropMonitoringServiceOuterClass.CropStatus.Builder getCropStatusListBuilder(
          int index) {
        return getCropStatusListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public smartagriculture.CropMonitoringServiceOuterClass.CropStatusOrBuilder getCropStatusListOrBuilder(
          int index) {
        if (cropStatusListBuilder_ == null) {
          return cropStatusList_.get(index);  } else {
          return cropStatusListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public java.util.List<? extends smartagriculture.CropMonitoringServiceOuterClass.CropStatusOrBuilder> 
           getCropStatusListOrBuilderList() {
        if (cropStatusListBuilder_ != null) {
          return cropStatusListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cropStatusList_);
        }
      }
      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public smartagriculture.CropMonitoringServiceOuterClass.CropStatus.Builder addCropStatusListBuilder() {
        return getCropStatusListFieldBuilder().addBuilder(
            smartagriculture.CropMonitoringServiceOuterClass.CropStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public smartagriculture.CropMonitoringServiceOuterClass.CropStatus.Builder addCropStatusListBuilder(
          int index) {
        return getCropStatusListFieldBuilder().addBuilder(
            index, smartagriculture.CropMonitoringServiceOuterClass.CropStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .smartagriculture.CropStatus cropStatusList = 1;</code>
       */
      public java.util.List<smartagriculture.CropMonitoringServiceOuterClass.CropStatus.Builder> 
           getCropStatusListBuilderList() {
        return getCropStatusListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          smartagriculture.CropMonitoringServiceOuterClass.CropStatus, smartagriculture.CropMonitoringServiceOuterClass.CropStatus.Builder, smartagriculture.CropMonitoringServiceOuterClass.CropStatusOrBuilder> 
          getCropStatusListFieldBuilder() {
        if (cropStatusListBuilder_ == null) {
          cropStatusListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              smartagriculture.CropMonitoringServiceOuterClass.CropStatus, smartagriculture.CropMonitoringServiceOuterClass.CropStatus.Builder, smartagriculture.CropMonitoringServiceOuterClass.CropStatusOrBuilder>(
                  cropStatusList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          cropStatusList_ = null;
        }
        return cropStatusListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smartagriculture.CropStatusList)
    }

    // @@protoc_insertion_point(class_scope:smartagriculture.CropStatusList)
    private static final smartagriculture.CropMonitoringServiceOuterClass.CropStatusList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smartagriculture.CropMonitoringServiceOuterClass.CropStatusList();
    }

    public static smartagriculture.CropMonitoringServiceOuterClass.CropStatusList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CropStatusList>
        PARSER = new com.google.protobuf.AbstractParser<CropStatusList>() {
      @java.lang.Override
      public CropStatusList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CropStatusList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CropStatusList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CropStatusList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smartagriculture.CropMonitoringServiceOuterClass.CropStatusList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartagriculture_CropId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartagriculture_CropId_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartagriculture_CropStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartagriculture_CropStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartagriculture_CropStatusList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartagriculture_CropStatusList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033CropMonitoringService.proto\022\020smartagri" +
      "culture\032\033google/protobuf/empty.proto\"\024\n\006" +
      "CropId\022\n\n\002id\030\001 \001(\005\"c\n\nCropStatus\022\n\n\002id\030\001" +
      " \001(\005\022\016\n\006status\030\002 \001(\t\022\023\n\013growthStage\030\003 \001(" +
      "\t\022\r\n\005pests\030\004 \003(\t\022\025\n\rmoistureLevel\030\005 \001(\002\"" +
      "F\n\016CropStatusList\0224\n\016cropStatusList\030\001 \003(" +
      "\0132\034.smartagriculture.CropStatus2\262\001\n\025Crop" +
      "MonitoringService\022L\n\020getAllCropStatus\022\026." +
      "google.protobuf.Empty\032 .smartagriculture" +
      ".CropStatusList\022K\n\021getCropStatusById\022\030.s" +
      "martagriculture.CropId\032\034.smartagricultur" +
      "e.CropStatusb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_smartagriculture_CropId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartagriculture_CropId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartagriculture_CropId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_smartagriculture_CropStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartagriculture_CropStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartagriculture_CropStatus_descriptor,
        new java.lang.String[] { "Id", "Status", "GrowthStage", "Pests", "MoistureLevel", });
    internal_static_smartagriculture_CropStatusList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartagriculture_CropStatusList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartagriculture_CropStatusList_descriptor,
        new java.lang.String[] { "CropStatusList", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
