// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataAnalysisService.proto

package smartagriculture;

public final class DataAnalysisServiceOuterClass {
  private DataAnalysisServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SensorDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smartagriculture.SensorData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float temperature = 1;</code>
     */
    float getTemperature();

    /**
     * <code>float humidity = 2;</code>
     */
    float getHumidity();

    /**
     * <code>float lightIntensity = 3;</code>
     */
    float getLightIntensity();
  }
  /**
   * Protobuf type {@code smartagriculture.SensorData}
   */
  public  static final class SensorData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smartagriculture.SensorData)
      SensorDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SensorData.newBuilder() to construct.
    private SensorData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SensorData() {
      temperature_ = 0F;
      humidity_ = 0F;
      lightIntensity_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SensorData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              temperature_ = input.readFloat();
              break;
            }
            case 21: {

              humidity_ = input.readFloat();
              break;
            }
            case 29: {

              lightIntensity_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartagriculture.DataAnalysisServiceOuterClass.internal_static_smartagriculture_SensorData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartagriculture.DataAnalysisServiceOuterClass.internal_static_smartagriculture_SensorData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartagriculture.DataAnalysisServiceOuterClass.SensorData.class, smartagriculture.DataAnalysisServiceOuterClass.SensorData.Builder.class);
    }

    public static final int TEMPERATURE_FIELD_NUMBER = 1;
    private float temperature_;
    /**
     * <code>float temperature = 1;</code>
     */
    public float getTemperature() {
      return temperature_;
    }

    public static final int HUMIDITY_FIELD_NUMBER = 2;
    private float humidity_;
    /**
     * <code>float humidity = 2;</code>
     */
    public float getHumidity() {
      return humidity_;
    }

    public static final int LIGHTINTENSITY_FIELD_NUMBER = 3;
    private float lightIntensity_;
    /**
     * <code>float lightIntensity = 3;</code>
     */
    public float getLightIntensity() {
      return lightIntensity_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (temperature_ != 0F) {
        output.writeFloat(1, temperature_);
      }
      if (humidity_ != 0F) {
        output.writeFloat(2, humidity_);
      }
      if (lightIntensity_ != 0F) {
        output.writeFloat(3, lightIntensity_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (temperature_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, temperature_);
      }
      if (humidity_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, humidity_);
      }
      if (lightIntensity_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, lightIntensity_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smartagriculture.DataAnalysisServiceOuterClass.SensorData)) {
        return super.equals(obj);
      }
      smartagriculture.DataAnalysisServiceOuterClass.SensorData other = (smartagriculture.DataAnalysisServiceOuterClass.SensorData) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getTemperature())
          == java.lang.Float.floatToIntBits(
              other.getTemperature()));
      result = result && (
          java.lang.Float.floatToIntBits(getHumidity())
          == java.lang.Float.floatToIntBits(
              other.getHumidity()));
      result = result && (
          java.lang.Float.floatToIntBits(getLightIntensity())
          == java.lang.Float.floatToIntBits(
              other.getLightIntensity()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTemperature());
      hash = (37 * hash) + HUMIDITY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHumidity());
      hash = (37 * hash) + LIGHTINTENSITY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLightIntensity());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smartagriculture.DataAnalysisServiceOuterClass.SensorData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smartagriculture.DataAnalysisServiceOuterClass.SensorData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code smartagriculture.SensorData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smartagriculture.SensorData)
        smartagriculture.DataAnalysisServiceOuterClass.SensorDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartagriculture.DataAnalysisServiceOuterClass.internal_static_smartagriculture_SensorData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartagriculture.DataAnalysisServiceOuterClass.internal_static_smartagriculture_SensorData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smartagriculture.DataAnalysisServiceOuterClass.SensorData.class, smartagriculture.DataAnalysisServiceOuterClass.SensorData.Builder.class);
      }

      // Construct using smartagriculture.DataAnalysisServiceOuterClass.SensorData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        temperature_ = 0F;

        humidity_ = 0F;

        lightIntensity_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartagriculture.DataAnalysisServiceOuterClass.internal_static_smartagriculture_SensorData_descriptor;
      }

      @java.lang.Override
      public smartagriculture.DataAnalysisServiceOuterClass.SensorData getDefaultInstanceForType() {
        return smartagriculture.DataAnalysisServiceOuterClass.SensorData.getDefaultInstance();
      }

      @java.lang.Override
      public smartagriculture.DataAnalysisServiceOuterClass.SensorData build() {
        smartagriculture.DataAnalysisServiceOuterClass.SensorData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smartagriculture.DataAnalysisServiceOuterClass.SensorData buildPartial() {
        smartagriculture.DataAnalysisServiceOuterClass.SensorData result = new smartagriculture.DataAnalysisServiceOuterClass.SensorData(this);
        result.temperature_ = temperature_;
        result.humidity_ = humidity_;
        result.lightIntensity_ = lightIntensity_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartagriculture.DataAnalysisServiceOuterClass.SensorData) {
          return mergeFrom((smartagriculture.DataAnalysisServiceOuterClass.SensorData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smartagriculture.DataAnalysisServiceOuterClass.SensorData other) {
        if (other == smartagriculture.DataAnalysisServiceOuterClass.SensorData.getDefaultInstance()) return this;
        if (other.getTemperature() != 0F) {
          setTemperature(other.getTemperature());
        }
        if (other.getHumidity() != 0F) {
          setHumidity(other.getHumidity());
        }
        if (other.getLightIntensity() != 0F) {
          setLightIntensity(other.getLightIntensity());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smartagriculture.DataAnalysisServiceOuterClass.SensorData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smartagriculture.DataAnalysisServiceOuterClass.SensorData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float temperature_ ;
      /**
       * <code>float temperature = 1;</code>
       */
      public float getTemperature() {
        return temperature_;
      }
      /**
       * <code>float temperature = 1;</code>
       */
      public Builder setTemperature(float value) {
        
        temperature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float temperature = 1;</code>
       */
      public Builder clearTemperature() {
        
        temperature_ = 0F;
        onChanged();
        return this;
      }

      private float humidity_ ;
      /**
       * <code>float humidity = 2;</code>
       */
      public float getHumidity() {
        return humidity_;
      }
      /**
       * <code>float humidity = 2;</code>
       */
      public Builder setHumidity(float value) {
        
        humidity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float humidity = 2;</code>
       */
      public Builder clearHumidity() {
        
        humidity_ = 0F;
        onChanged();
        return this;
      }

      private float lightIntensity_ ;
      /**
       * <code>float lightIntensity = 3;</code>
       */
      public float getLightIntensity() {
        return lightIntensity_;
      }
      /**
       * <code>float lightIntensity = 3;</code>
       */
      public Builder setLightIntensity(float value) {
        
        lightIntensity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float lightIntensity = 3;</code>
       */
      public Builder clearLightIntensity() {
        
        lightIntensity_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smartagriculture.SensorData)
    }

    // @@protoc_insertion_point(class_scope:smartagriculture.SensorData)
    private static final smartagriculture.DataAnalysisServiceOuterClass.SensorData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smartagriculture.DataAnalysisServiceOuterClass.SensorData();
    }

    public static smartagriculture.DataAnalysisServiceOuterClass.SensorData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SensorData>
        PARSER = new com.google.protobuf.AbstractParser<SensorData>() {
      @java.lang.Override
      public SensorData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SensorData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SensorData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SensorData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smartagriculture.DataAnalysisServiceOuterClass.SensorData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SensorAnalysisOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smartagriculture.SensorAnalysis)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string analysisResult = 1;</code>
     */
    java.lang.String getAnalysisResult();
    /**
     * <code>string analysisResult = 1;</code>
     */
    com.google.protobuf.ByteString
        getAnalysisResultBytes();
  }
  /**
   * Protobuf type {@code smartagriculture.SensorAnalysis}
   */
  public  static final class SensorAnalysis extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smartagriculture.SensorAnalysis)
      SensorAnalysisOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SensorAnalysis.newBuilder() to construct.
    private SensorAnalysis(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SensorAnalysis() {
      analysisResult_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SensorAnalysis(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              analysisResult_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartagriculture.DataAnalysisServiceOuterClass.internal_static_smartagriculture_SensorAnalysis_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartagriculture.DataAnalysisServiceOuterClass.internal_static_smartagriculture_SensorAnalysis_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis.class, smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis.Builder.class);
    }

    public static final int ANALYSISRESULT_FIELD_NUMBER = 1;
    private volatile java.lang.Object analysisResult_;
    /**
     * <code>string analysisResult = 1;</code>
     */
    public java.lang.String getAnalysisResult() {
      java.lang.Object ref = analysisResult_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        analysisResult_ = s;
        return s;
      }
    }
    /**
     * <code>string analysisResult = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAnalysisResultBytes() {
      java.lang.Object ref = analysisResult_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        analysisResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAnalysisResultBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, analysisResult_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAnalysisResultBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, analysisResult_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis)) {
        return super.equals(obj);
      }
      smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis other = (smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis) obj;

      boolean result = true;
      result = result && getAnalysisResult()
          .equals(other.getAnalysisResult());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ANALYSISRESULT_FIELD_NUMBER;
      hash = (53 * hash) + getAnalysisResult().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code smartagriculture.SensorAnalysis}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smartagriculture.SensorAnalysis)
        smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysisOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartagriculture.DataAnalysisServiceOuterClass.internal_static_smartagriculture_SensorAnalysis_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartagriculture.DataAnalysisServiceOuterClass.internal_static_smartagriculture_SensorAnalysis_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis.class, smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis.Builder.class);
      }

      // Construct using smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        analysisResult_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartagriculture.DataAnalysisServiceOuterClass.internal_static_smartagriculture_SensorAnalysis_descriptor;
      }

      @java.lang.Override
      public smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis getDefaultInstanceForType() {
        return smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis.getDefaultInstance();
      }

      @java.lang.Override
      public smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis build() {
        smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis buildPartial() {
        smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis result = new smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis(this);
        result.analysisResult_ = analysisResult_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis) {
          return mergeFrom((smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis other) {
        if (other == smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis.getDefaultInstance()) return this;
        if (!other.getAnalysisResult().isEmpty()) {
          analysisResult_ = other.analysisResult_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object analysisResult_ = "";
      /**
       * <code>string analysisResult = 1;</code>
       */
      public java.lang.String getAnalysisResult() {
        java.lang.Object ref = analysisResult_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          analysisResult_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string analysisResult = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAnalysisResultBytes() {
        java.lang.Object ref = analysisResult_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          analysisResult_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string analysisResult = 1;</code>
       */
      public Builder setAnalysisResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        analysisResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string analysisResult = 1;</code>
       */
      public Builder clearAnalysisResult() {
        
        analysisResult_ = getDefaultInstance().getAnalysisResult();
        onChanged();
        return this;
      }
      /**
       * <code>string analysisResult = 1;</code>
       */
      public Builder setAnalysisResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        analysisResult_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smartagriculture.SensorAnalysis)
    }

    // @@protoc_insertion_point(class_scope:smartagriculture.SensorAnalysis)
    private static final smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis();
    }

    public static smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SensorAnalysis>
        PARSER = new com.google.protobuf.AbstractParser<SensorAnalysis>() {
      @java.lang.Override
      public SensorAnalysis parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SensorAnalysis(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SensorAnalysis> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SensorAnalysis> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smartagriculture.DataAnalysisServiceOuterClass.SensorAnalysis getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartagriculture_SensorData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartagriculture_SensorData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartagriculture_SensorAnalysis_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartagriculture_SensorAnalysis_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031DataAnalysisService.proto\022\020smartagricu" +
      "lture\"K\n\nSensorData\022\023\n\013temperature\030\001 \001(\002" +
      "\022\020\n\010humidity\030\002 \001(\002\022\026\n\016lightIntensity\030\003 \001" +
      "(\002\"(\n\016SensorAnalysis\022\026\n\016analysisResult\030\001" +
      " \001(\t2j\n\023DataAnalysisService\022S\n\021analyzeSe" +
      "nsorData\022\034.smartagriculture.SensorData\032 " +
      ".smartagriculture.SensorAnalysisb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartagriculture_SensorData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartagriculture_SensorData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartagriculture_SensorData_descriptor,
        new java.lang.String[] { "Temperature", "Humidity", "LightIntensity", });
    internal_static_smartagriculture_SensorAnalysis_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartagriculture_SensorAnalysis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartagriculture_SensorAnalysis_descriptor,
        new java.lang.String[] { "AnalysisResult", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
