// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CropManagementService.proto

package smartfarming;

public final class CropManagementServiceOuterClass {
  private CropManagementServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AdjustPHRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smartfarming.AdjustPHRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Unique identifier for the block
     * </pre>
     *
     * <code>int32 blockId = 1;</code>
     */
    int getBlockId();

    /**
     * <pre>
     * Target pH level
     * </pre>
     *
     * <code>double PHLevel = 2;</code>
     */
    double getPHLevel();
  }
  /**
   * <pre>
   * Message for requesting adjustment of pH level for a specific block
   * </pre>
   *
   * Protobuf type {@code smartfarming.AdjustPHRequest}
   */
  public  static final class AdjustPHRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smartfarming.AdjustPHRequest)
      AdjustPHRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AdjustPHRequest.newBuilder() to construct.
    private AdjustPHRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdjustPHRequest() {
      blockId_ = 0;
      pHLevel_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AdjustPHRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              blockId_ = input.readInt32();
              break;
            }
            case 17: {

              pHLevel_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_AdjustPHRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_AdjustPHRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartfarming.CropManagementServiceOuterClass.AdjustPHRequest.class, smartfarming.CropManagementServiceOuterClass.AdjustPHRequest.Builder.class);
    }

    public static final int BLOCKID_FIELD_NUMBER = 1;
    private int blockId_;
    /**
     * <pre>
     * Unique identifier for the block
     * </pre>
     *
     * <code>int32 blockId = 1;</code>
     */
    public int getBlockId() {
      return blockId_;
    }

    public static final int PHLEVEL_FIELD_NUMBER = 2;
    private double pHLevel_;
    /**
     * <pre>
     * Target pH level
     * </pre>
     *
     * <code>double PHLevel = 2;</code>
     */
    public double getPHLevel() {
      return pHLevel_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (blockId_ != 0) {
        output.writeInt32(1, blockId_);
      }
      if (pHLevel_ != 0D) {
        output.writeDouble(2, pHLevel_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (blockId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, blockId_);
      }
      if (pHLevel_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, pHLevel_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smartfarming.CropManagementServiceOuterClass.AdjustPHRequest)) {
        return super.equals(obj);
      }
      smartfarming.CropManagementServiceOuterClass.AdjustPHRequest other = (smartfarming.CropManagementServiceOuterClass.AdjustPHRequest) obj;

      boolean result = true;
      result = result && (getBlockId()
          == other.getBlockId());
      result = result && (
          java.lang.Double.doubleToLongBits(getPHLevel())
          == java.lang.Double.doubleToLongBits(
              other.getPHLevel()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLOCKID_FIELD_NUMBER;
      hash = (53 * hash) + getBlockId();
      hash = (37 * hash) + PHLEVEL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPHLevel()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smartfarming.CropManagementServiceOuterClass.AdjustPHRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustPHRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustPHRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustPHRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustPHRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustPHRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustPHRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustPHRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustPHRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustPHRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustPHRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustPHRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smartfarming.CropManagementServiceOuterClass.AdjustPHRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message for requesting adjustment of pH level for a specific block
     * </pre>
     *
     * Protobuf type {@code smartfarming.AdjustPHRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smartfarming.AdjustPHRequest)
        smartfarming.CropManagementServiceOuterClass.AdjustPHRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_AdjustPHRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_AdjustPHRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smartfarming.CropManagementServiceOuterClass.AdjustPHRequest.class, smartfarming.CropManagementServiceOuterClass.AdjustPHRequest.Builder.class);
      }

      // Construct using smartfarming.CropManagementServiceOuterClass.AdjustPHRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        blockId_ = 0;

        pHLevel_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_AdjustPHRequest_descriptor;
      }

      @java.lang.Override
      public smartfarming.CropManagementServiceOuterClass.AdjustPHRequest getDefaultInstanceForType() {
        return smartfarming.CropManagementServiceOuterClass.AdjustPHRequest.getDefaultInstance();
      }

      @java.lang.Override
      public smartfarming.CropManagementServiceOuterClass.AdjustPHRequest build() {
        smartfarming.CropManagementServiceOuterClass.AdjustPHRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smartfarming.CropManagementServiceOuterClass.AdjustPHRequest buildPartial() {
        smartfarming.CropManagementServiceOuterClass.AdjustPHRequest result = new smartfarming.CropManagementServiceOuterClass.AdjustPHRequest(this);
        result.blockId_ = blockId_;
        result.pHLevel_ = pHLevel_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartfarming.CropManagementServiceOuterClass.AdjustPHRequest) {
          return mergeFrom((smartfarming.CropManagementServiceOuterClass.AdjustPHRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smartfarming.CropManagementServiceOuterClass.AdjustPHRequest other) {
        if (other == smartfarming.CropManagementServiceOuterClass.AdjustPHRequest.getDefaultInstance()) return this;
        if (other.getBlockId() != 0) {
          setBlockId(other.getBlockId());
        }
        if (other.getPHLevel() != 0D) {
          setPHLevel(other.getPHLevel());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smartfarming.CropManagementServiceOuterClass.AdjustPHRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smartfarming.CropManagementServiceOuterClass.AdjustPHRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int blockId_ ;
      /**
       * <pre>
       * Unique identifier for the block
       * </pre>
       *
       * <code>int32 blockId = 1;</code>
       */
      public int getBlockId() {
        return blockId_;
      }
      /**
       * <pre>
       * Unique identifier for the block
       * </pre>
       *
       * <code>int32 blockId = 1;</code>
       */
      public Builder setBlockId(int value) {
        
        blockId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique identifier for the block
       * </pre>
       *
       * <code>int32 blockId = 1;</code>
       */
      public Builder clearBlockId() {
        
        blockId_ = 0;
        onChanged();
        return this;
      }

      private double pHLevel_ ;
      /**
       * <pre>
       * Target pH level
       * </pre>
       *
       * <code>double PHLevel = 2;</code>
       */
      public double getPHLevel() {
        return pHLevel_;
      }
      /**
       * <pre>
       * Target pH level
       * </pre>
       *
       * <code>double PHLevel = 2;</code>
       */
      public Builder setPHLevel(double value) {
        
        pHLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Target pH level
       * </pre>
       *
       * <code>double PHLevel = 2;</code>
       */
      public Builder clearPHLevel() {
        
        pHLevel_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smartfarming.AdjustPHRequest)
    }

    // @@protoc_insertion_point(class_scope:smartfarming.AdjustPHRequest)
    private static final smartfarming.CropManagementServiceOuterClass.AdjustPHRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smartfarming.CropManagementServiceOuterClass.AdjustPHRequest();
    }

    public static smartfarming.CropManagementServiceOuterClass.AdjustPHRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AdjustPHRequest>
        PARSER = new com.google.protobuf.AbstractParser<AdjustPHRequest>() {
      @java.lang.Override
      public AdjustPHRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdjustPHRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AdjustPHRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdjustPHRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smartfarming.CropManagementServiceOuterClass.AdjustPHRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PestControlRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smartfarming.PestControlRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Unique identifier for the block
     * </pre>
     *
     * <code>int32 blockId = 1;</code>
     */
    int getBlockId();
  }
  /**
   * <pre>
   * Message for requesting pest control for a specific block
   * </pre>
   *
   * Protobuf type {@code smartfarming.PestControlRequest}
   */
  public  static final class PestControlRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smartfarming.PestControlRequest)
      PestControlRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PestControlRequest.newBuilder() to construct.
    private PestControlRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PestControlRequest() {
      blockId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PestControlRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              blockId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_PestControlRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_PestControlRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartfarming.CropManagementServiceOuterClass.PestControlRequest.class, smartfarming.CropManagementServiceOuterClass.PestControlRequest.Builder.class);
    }

    public static final int BLOCKID_FIELD_NUMBER = 1;
    private int blockId_;
    /**
     * <pre>
     * Unique identifier for the block
     * </pre>
     *
     * <code>int32 blockId = 1;</code>
     */
    public int getBlockId() {
      return blockId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (blockId_ != 0) {
        output.writeInt32(1, blockId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (blockId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, blockId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smartfarming.CropManagementServiceOuterClass.PestControlRequest)) {
        return super.equals(obj);
      }
      smartfarming.CropManagementServiceOuterClass.PestControlRequest other = (smartfarming.CropManagementServiceOuterClass.PestControlRequest) obj;

      boolean result = true;
      result = result && (getBlockId()
          == other.getBlockId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLOCKID_FIELD_NUMBER;
      hash = (53 * hash) + getBlockId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smartfarming.CropManagementServiceOuterClass.PestControlRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.CropManagementServiceOuterClass.PestControlRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.PestControlRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.CropManagementServiceOuterClass.PestControlRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.PestControlRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.CropManagementServiceOuterClass.PestControlRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.PestControlRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartfarming.CropManagementServiceOuterClass.PestControlRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.PestControlRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smartfarming.CropManagementServiceOuterClass.PestControlRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.PestControlRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartfarming.CropManagementServiceOuterClass.PestControlRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smartfarming.CropManagementServiceOuterClass.PestControlRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message for requesting pest control for a specific block
     * </pre>
     *
     * Protobuf type {@code smartfarming.PestControlRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smartfarming.PestControlRequest)
        smartfarming.CropManagementServiceOuterClass.PestControlRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_PestControlRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_PestControlRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smartfarming.CropManagementServiceOuterClass.PestControlRequest.class, smartfarming.CropManagementServiceOuterClass.PestControlRequest.Builder.class);
      }

      // Construct using smartfarming.CropManagementServiceOuterClass.PestControlRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        blockId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_PestControlRequest_descriptor;
      }

      @java.lang.Override
      public smartfarming.CropManagementServiceOuterClass.PestControlRequest getDefaultInstanceForType() {
        return smartfarming.CropManagementServiceOuterClass.PestControlRequest.getDefaultInstance();
      }

      @java.lang.Override
      public smartfarming.CropManagementServiceOuterClass.PestControlRequest build() {
        smartfarming.CropManagementServiceOuterClass.PestControlRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smartfarming.CropManagementServiceOuterClass.PestControlRequest buildPartial() {
        smartfarming.CropManagementServiceOuterClass.PestControlRequest result = new smartfarming.CropManagementServiceOuterClass.PestControlRequest(this);
        result.blockId_ = blockId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartfarming.CropManagementServiceOuterClass.PestControlRequest) {
          return mergeFrom((smartfarming.CropManagementServiceOuterClass.PestControlRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smartfarming.CropManagementServiceOuterClass.PestControlRequest other) {
        if (other == smartfarming.CropManagementServiceOuterClass.PestControlRequest.getDefaultInstance()) return this;
        if (other.getBlockId() != 0) {
          setBlockId(other.getBlockId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smartfarming.CropManagementServiceOuterClass.PestControlRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smartfarming.CropManagementServiceOuterClass.PestControlRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int blockId_ ;
      /**
       * <pre>
       * Unique identifier for the block
       * </pre>
       *
       * <code>int32 blockId = 1;</code>
       */
      public int getBlockId() {
        return blockId_;
      }
      /**
       * <pre>
       * Unique identifier for the block
       * </pre>
       *
       * <code>int32 blockId = 1;</code>
       */
      public Builder setBlockId(int value) {
        
        blockId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique identifier for the block
       * </pre>
       *
       * <code>int32 blockId = 1;</code>
       */
      public Builder clearBlockId() {
        
        blockId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smartfarming.PestControlRequest)
    }

    // @@protoc_insertion_point(class_scope:smartfarming.PestControlRequest)
    private static final smartfarming.CropManagementServiceOuterClass.PestControlRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smartfarming.CropManagementServiceOuterClass.PestControlRequest();
    }

    public static smartfarming.CropManagementServiceOuterClass.PestControlRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PestControlRequest>
        PARSER = new com.google.protobuf.AbstractParser<PestControlRequest>() {
      @java.lang.Override
      public PestControlRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PestControlRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PestControlRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PestControlRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smartfarming.CropManagementServiceOuterClass.PestControlRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AdjustLightIntensityRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smartfarming.AdjustLightIntensityRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Unique identifier for the block
     * </pre>
     *
     * <code>int32 blockId = 1;</code>
     */
    int getBlockId();

    /**
     * <pre>
     * Target light intensity
     * </pre>
     *
     * <code>double lightIntensity = 2;</code>
     */
    double getLightIntensity();
  }
  /**
   * <pre>
   * Message for requesting adjustment of light intensity for a specific block
   * </pre>
   *
   * Protobuf type {@code smartfarming.AdjustLightIntensityRequest}
   */
  public  static final class AdjustLightIntensityRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smartfarming.AdjustLightIntensityRequest)
      AdjustLightIntensityRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AdjustLightIntensityRequest.newBuilder() to construct.
    private AdjustLightIntensityRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdjustLightIntensityRequest() {
      blockId_ = 0;
      lightIntensity_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AdjustLightIntensityRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              blockId_ = input.readInt32();
              break;
            }
            case 17: {

              lightIntensity_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_AdjustLightIntensityRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_AdjustLightIntensityRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest.class, smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest.Builder.class);
    }

    public static final int BLOCKID_FIELD_NUMBER = 1;
    private int blockId_;
    /**
     * <pre>
     * Unique identifier for the block
     * </pre>
     *
     * <code>int32 blockId = 1;</code>
     */
    public int getBlockId() {
      return blockId_;
    }

    public static final int LIGHTINTENSITY_FIELD_NUMBER = 2;
    private double lightIntensity_;
    /**
     * <pre>
     * Target light intensity
     * </pre>
     *
     * <code>double lightIntensity = 2;</code>
     */
    public double getLightIntensity() {
      return lightIntensity_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (blockId_ != 0) {
        output.writeInt32(1, blockId_);
      }
      if (lightIntensity_ != 0D) {
        output.writeDouble(2, lightIntensity_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (blockId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, blockId_);
      }
      if (lightIntensity_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, lightIntensity_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest)) {
        return super.equals(obj);
      }
      smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest other = (smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest) obj;

      boolean result = true;
      result = result && (getBlockId()
          == other.getBlockId());
      result = result && (
          java.lang.Double.doubleToLongBits(getLightIntensity())
          == java.lang.Double.doubleToLongBits(
              other.getLightIntensity()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLOCKID_FIELD_NUMBER;
      hash = (53 * hash) + getBlockId();
      hash = (37 * hash) + LIGHTINTENSITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLightIntensity()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message for requesting adjustment of light intensity for a specific block
     * </pre>
     *
     * Protobuf type {@code smartfarming.AdjustLightIntensityRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smartfarming.AdjustLightIntensityRequest)
        smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_AdjustLightIntensityRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_AdjustLightIntensityRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest.class, smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest.Builder.class);
      }

      // Construct using smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        blockId_ = 0;

        lightIntensity_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_AdjustLightIntensityRequest_descriptor;
      }

      @java.lang.Override
      public smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest getDefaultInstanceForType() {
        return smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest.getDefaultInstance();
      }

      @java.lang.Override
      public smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest build() {
        smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest buildPartial() {
        smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest result = new smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest(this);
        result.blockId_ = blockId_;
        result.lightIntensity_ = lightIntensity_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest) {
          return mergeFrom((smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest other) {
        if (other == smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest.getDefaultInstance()) return this;
        if (other.getBlockId() != 0) {
          setBlockId(other.getBlockId());
        }
        if (other.getLightIntensity() != 0D) {
          setLightIntensity(other.getLightIntensity());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int blockId_ ;
      /**
       * <pre>
       * Unique identifier for the block
       * </pre>
       *
       * <code>int32 blockId = 1;</code>
       */
      public int getBlockId() {
        return blockId_;
      }
      /**
       * <pre>
       * Unique identifier for the block
       * </pre>
       *
       * <code>int32 blockId = 1;</code>
       */
      public Builder setBlockId(int value) {
        
        blockId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique identifier for the block
       * </pre>
       *
       * <code>int32 blockId = 1;</code>
       */
      public Builder clearBlockId() {
        
        blockId_ = 0;
        onChanged();
        return this;
      }

      private double lightIntensity_ ;
      /**
       * <pre>
       * Target light intensity
       * </pre>
       *
       * <code>double lightIntensity = 2;</code>
       */
      public double getLightIntensity() {
        return lightIntensity_;
      }
      /**
       * <pre>
       * Target light intensity
       * </pre>
       *
       * <code>double lightIntensity = 2;</code>
       */
      public Builder setLightIntensity(double value) {
        
        lightIntensity_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Target light intensity
       * </pre>
       *
       * <code>double lightIntensity = 2;</code>
       */
      public Builder clearLightIntensity() {
        
        lightIntensity_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smartfarming.AdjustLightIntensityRequest)
    }

    // @@protoc_insertion_point(class_scope:smartfarming.AdjustLightIntensityRequest)
    private static final smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest();
    }

    public static smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AdjustLightIntensityRequest>
        PARSER = new com.google.protobuf.AbstractParser<AdjustLightIntensityRequest>() {
      @java.lang.Override
      public AdjustLightIntensityRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdjustLightIntensityRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AdjustLightIntensityRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdjustLightIntensityRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smartfarming.CropManagementServiceOuterClass.AdjustLightIntensityRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AdjustResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smartfarming.AdjustResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Indicates if the adjustment action was successful or not
     * </pre>
     *
     * <code>bool success = 1;</code>
     */
    boolean getSuccess();

    /**
     * <pre>
     * Additional message providing details about the adjustment action
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * Additional message providing details about the adjustment action
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * Message for representing the response of an adjustment action
   * </pre>
   *
   * Protobuf type {@code smartfarming.AdjustResponse}
   */
  public  static final class AdjustResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smartfarming.AdjustResponse)
      AdjustResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AdjustResponse.newBuilder() to construct.
    private AdjustResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdjustResponse() {
      success_ = false;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AdjustResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_AdjustResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_AdjustResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartfarming.CropManagementServiceOuterClass.AdjustResponse.class, smartfarming.CropManagementServiceOuterClass.AdjustResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <pre>
     * Indicates if the adjustment action was successful or not
     * </pre>
     *
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * Additional message providing details about the adjustment action
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Additional message providing details about the adjustment action
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smartfarming.CropManagementServiceOuterClass.AdjustResponse)) {
        return super.equals(obj);
      }
      smartfarming.CropManagementServiceOuterClass.AdjustResponse other = (smartfarming.CropManagementServiceOuterClass.AdjustResponse) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smartfarming.CropManagementServiceOuterClass.AdjustResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartfarming.CropManagementServiceOuterClass.AdjustResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smartfarming.CropManagementServiceOuterClass.AdjustResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message for representing the response of an adjustment action
     * </pre>
     *
     * Protobuf type {@code smartfarming.AdjustResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smartfarming.AdjustResponse)
        smartfarming.CropManagementServiceOuterClass.AdjustResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_AdjustResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_AdjustResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smartfarming.CropManagementServiceOuterClass.AdjustResponse.class, smartfarming.CropManagementServiceOuterClass.AdjustResponse.Builder.class);
      }

      // Construct using smartfarming.CropManagementServiceOuterClass.AdjustResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = false;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartfarming.CropManagementServiceOuterClass.internal_static_smartfarming_AdjustResponse_descriptor;
      }

      @java.lang.Override
      public smartfarming.CropManagementServiceOuterClass.AdjustResponse getDefaultInstanceForType() {
        return smartfarming.CropManagementServiceOuterClass.AdjustResponse.getDefaultInstance();
      }

      @java.lang.Override
      public smartfarming.CropManagementServiceOuterClass.AdjustResponse build() {
        smartfarming.CropManagementServiceOuterClass.AdjustResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smartfarming.CropManagementServiceOuterClass.AdjustResponse buildPartial() {
        smartfarming.CropManagementServiceOuterClass.AdjustResponse result = new smartfarming.CropManagementServiceOuterClass.AdjustResponse(this);
        result.success_ = success_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartfarming.CropManagementServiceOuterClass.AdjustResponse) {
          return mergeFrom((smartfarming.CropManagementServiceOuterClass.AdjustResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smartfarming.CropManagementServiceOuterClass.AdjustResponse other) {
        if (other == smartfarming.CropManagementServiceOuterClass.AdjustResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smartfarming.CropManagementServiceOuterClass.AdjustResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smartfarming.CropManagementServiceOuterClass.AdjustResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <pre>
       * Indicates if the adjustment action was successful or not
       * </pre>
       *
       * <code>bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <pre>
       * Indicates if the adjustment action was successful or not
       * </pre>
       *
       * <code>bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Indicates if the adjustment action was successful or not
       * </pre>
       *
       * <code>bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * Additional message providing details about the adjustment action
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Additional message providing details about the adjustment action
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Additional message providing details about the adjustment action
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Additional message providing details about the adjustment action
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Additional message providing details about the adjustment action
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smartfarming.AdjustResponse)
    }

    // @@protoc_insertion_point(class_scope:smartfarming.AdjustResponse)
    private static final smartfarming.CropManagementServiceOuterClass.AdjustResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smartfarming.CropManagementServiceOuterClass.AdjustResponse();
    }

    public static smartfarming.CropManagementServiceOuterClass.AdjustResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AdjustResponse>
        PARSER = new com.google.protobuf.AbstractParser<AdjustResponse>() {
      @java.lang.Override
      public AdjustResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdjustResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AdjustResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdjustResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smartfarming.CropManagementServiceOuterClass.AdjustResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartfarming_AdjustPHRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartfarming_AdjustPHRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartfarming_PestControlRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartfarming_PestControlRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartfarming_AdjustLightIntensityRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartfarming_AdjustLightIntensityRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartfarming_AdjustResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartfarming_AdjustResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033CropManagementService.proto\022\014smartfarm" +
      "ing\"3\n\017AdjustPHRequest\022\017\n\007blockId\030\001 \001(\005\022" +
      "\017\n\007PHLevel\030\002 \001(\001\"%\n\022PestControlRequest\022\017" +
      "\n\007blockId\030\001 \001(\005\"F\n\033AdjustLightIntensityR" +
      "equest\022\017\n\007blockId\030\001 \001(\005\022\026\n\016lightIntensit" +
      "y\030\002 \001(\001\"2\n\016AdjustResponse\022\017\n\007success\030\001 \001" +
      "(\010\022\017\n\007message\030\002 \001(\t2\220\002\n\025CropManagementSe" +
      "rvice\022G\n\010AdjustPh\022\035.smartfarming.AdjustP" +
      "HRequest\032\034.smartfarming.AdjustResponse\022M" +
      "\n\013PestControl\022 .smartfarming.PestControl" +
      "Request\032\034.smartfarming.AdjustResponse\022_\n" +
      "\024AdjustLightIntensity\022).smartfarming.Adj" +
      "ustLightIntensityRequest\032\034.smartfarming." +
      "AdjustResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartfarming_AdjustPHRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartfarming_AdjustPHRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartfarming_AdjustPHRequest_descriptor,
        new java.lang.String[] { "BlockId", "PHLevel", });
    internal_static_smartfarming_PestControlRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartfarming_PestControlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartfarming_PestControlRequest_descriptor,
        new java.lang.String[] { "BlockId", });
    internal_static_smartfarming_AdjustLightIntensityRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartfarming_AdjustLightIntensityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartfarming_AdjustLightIntensityRequest_descriptor,
        new java.lang.String[] { "BlockId", "LightIntensity", });
    internal_static_smartfarming_AdjustResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smartfarming_AdjustResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartfarming_AdjustResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
