// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WaterAndFertilizerService.proto

package smartfarming;

public final class WaterAndFertilizerServiceOuterClass {
  private WaterAndFertilizerServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WaterRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smartfarming.WaterRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Unique identifier for the block
     * </pre>
     *
     * <code>int32 blockId = 1;</code>
     */
    int getBlockId();

    /**
     * <pre>
     * Time at which watering is requested, watering time for seconds
     * </pre>
     *
     * <code>double wateringTime = 2;</code>
     */
    double getWateringTime();
  }
  /**
   * <pre>
   * Message for requesting water for a specific block
   * </pre>
   *
   * Protobuf type {@code smartfarming.WaterRequest}
   */
  public  static final class WaterRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smartfarming.WaterRequest)
      WaterRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WaterRequest.newBuilder() to construct.
    private WaterRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WaterRequest() {
      blockId_ = 0;
      wateringTime_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WaterRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              blockId_ = input.readInt32();
              break;
            }
            case 17: {

              wateringTime_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartfarming.WaterAndFertilizerServiceOuterClass.internal_static_smartfarming_WaterRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartfarming.WaterAndFertilizerServiceOuterClass.internal_static_smartfarming_WaterRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest.class, smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest.Builder.class);
    }

    public static final int BLOCKID_FIELD_NUMBER = 1;
    private int blockId_;
    /**
     * <pre>
     * Unique identifier for the block
     * </pre>
     *
     * <code>int32 blockId = 1;</code>
     */
    public int getBlockId() {
      return blockId_;
    }

    public static final int WATERINGTIME_FIELD_NUMBER = 2;
    private double wateringTime_;
    /**
     * <pre>
     * Time at which watering is requested, watering time for seconds
     * </pre>
     *
     * <code>double wateringTime = 2;</code>
     */
    public double getWateringTime() {
      return wateringTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (blockId_ != 0) {
        output.writeInt32(1, blockId_);
      }
      if (wateringTime_ != 0D) {
        output.writeDouble(2, wateringTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (blockId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, blockId_);
      }
      if (wateringTime_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, wateringTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest)) {
        return super.equals(obj);
      }
      smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest other = (smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest) obj;

      boolean result = true;
      result = result && (getBlockId()
          == other.getBlockId());
      result = result && (
          java.lang.Double.doubleToLongBits(getWateringTime())
          == java.lang.Double.doubleToLongBits(
              other.getWateringTime()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLOCKID_FIELD_NUMBER;
      hash = (53 * hash) + getBlockId();
      hash = (37 * hash) + WATERINGTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getWateringTime()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message for requesting water for a specific block
     * </pre>
     *
     * Protobuf type {@code smartfarming.WaterRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smartfarming.WaterRequest)
        smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartfarming.WaterAndFertilizerServiceOuterClass.internal_static_smartfarming_WaterRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartfarming.WaterAndFertilizerServiceOuterClass.internal_static_smartfarming_WaterRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest.class, smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest.Builder.class);
      }

      // Construct using smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        blockId_ = 0;

        wateringTime_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartfarming.WaterAndFertilizerServiceOuterClass.internal_static_smartfarming_WaterRequest_descriptor;
      }

      @java.lang.Override
      public smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest getDefaultInstanceForType() {
        return smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest.getDefaultInstance();
      }

      @java.lang.Override
      public smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest build() {
        smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest buildPartial() {
        smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest result = new smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest(this);
        result.blockId_ = blockId_;
        result.wateringTime_ = wateringTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest) {
          return mergeFrom((smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest other) {
        if (other == smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest.getDefaultInstance()) return this;
        if (other.getBlockId() != 0) {
          setBlockId(other.getBlockId());
        }
        if (other.getWateringTime() != 0D) {
          setWateringTime(other.getWateringTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int blockId_ ;
      /**
       * <pre>
       * Unique identifier for the block
       * </pre>
       *
       * <code>int32 blockId = 1;</code>
       */
      public int getBlockId() {
        return blockId_;
      }
      /**
       * <pre>
       * Unique identifier for the block
       * </pre>
       *
       * <code>int32 blockId = 1;</code>
       */
      public Builder setBlockId(int value) {
        
        blockId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique identifier for the block
       * </pre>
       *
       * <code>int32 blockId = 1;</code>
       */
      public Builder clearBlockId() {
        
        blockId_ = 0;
        onChanged();
        return this;
      }

      private double wateringTime_ ;
      /**
       * <pre>
       * Time at which watering is requested, watering time for seconds
       * </pre>
       *
       * <code>double wateringTime = 2;</code>
       */
      public double getWateringTime() {
        return wateringTime_;
      }
      /**
       * <pre>
       * Time at which watering is requested, watering time for seconds
       * </pre>
       *
       * <code>double wateringTime = 2;</code>
       */
      public Builder setWateringTime(double value) {
        
        wateringTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time at which watering is requested, watering time for seconds
       * </pre>
       *
       * <code>double wateringTime = 2;</code>
       */
      public Builder clearWateringTime() {
        
        wateringTime_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smartfarming.WaterRequest)
    }

    // @@protoc_insertion_point(class_scope:smartfarming.WaterRequest)
    private static final smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest();
    }

    public static smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WaterRequest>
        PARSER = new com.google.protobuf.AbstractParser<WaterRequest>() {
      @java.lang.Override
      public WaterRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WaterRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WaterRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WaterRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smartfarming.WaterAndFertilizerServiceOuterClass.WaterRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FertilizeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smartfarming.FertilizeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Unique identifier for the block
     * </pre>
     *
     * <code>int32 blockId = 1;</code>
     */
    int getBlockId();

    /**
     * <pre>
     * Amount of fertilizer to be applied
     * </pre>
     *
     * <code>double fertilizerAmount = 2;</code>
     */
    double getFertilizerAmount();
  }
  /**
   * <pre>
   * Message for requesting fertilization for a specific block
   * </pre>
   *
   * Protobuf type {@code smartfarming.FertilizeRequest}
   */
  public  static final class FertilizeRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smartfarming.FertilizeRequest)
      FertilizeRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FertilizeRequest.newBuilder() to construct.
    private FertilizeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FertilizeRequest() {
      blockId_ = 0;
      fertilizerAmount_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FertilizeRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              blockId_ = input.readInt32();
              break;
            }
            case 17: {

              fertilizerAmount_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartfarming.WaterAndFertilizerServiceOuterClass.internal_static_smartfarming_FertilizeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartfarming.WaterAndFertilizerServiceOuterClass.internal_static_smartfarming_FertilizeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest.class, smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest.Builder.class);
    }

    public static final int BLOCKID_FIELD_NUMBER = 1;
    private int blockId_;
    /**
     * <pre>
     * Unique identifier for the block
     * </pre>
     *
     * <code>int32 blockId = 1;</code>
     */
    public int getBlockId() {
      return blockId_;
    }

    public static final int FERTILIZERAMOUNT_FIELD_NUMBER = 2;
    private double fertilizerAmount_;
    /**
     * <pre>
     * Amount of fertilizer to be applied
     * </pre>
     *
     * <code>double fertilizerAmount = 2;</code>
     */
    public double getFertilizerAmount() {
      return fertilizerAmount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (blockId_ != 0) {
        output.writeInt32(1, blockId_);
      }
      if (fertilizerAmount_ != 0D) {
        output.writeDouble(2, fertilizerAmount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (blockId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, blockId_);
      }
      if (fertilizerAmount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, fertilizerAmount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest)) {
        return super.equals(obj);
      }
      smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest other = (smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest) obj;

      boolean result = true;
      result = result && (getBlockId()
          == other.getBlockId());
      result = result && (
          java.lang.Double.doubleToLongBits(getFertilizerAmount())
          == java.lang.Double.doubleToLongBits(
              other.getFertilizerAmount()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLOCKID_FIELD_NUMBER;
      hash = (53 * hash) + getBlockId();
      hash = (37 * hash) + FERTILIZERAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getFertilizerAmount()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message for requesting fertilization for a specific block
     * </pre>
     *
     * Protobuf type {@code smartfarming.FertilizeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smartfarming.FertilizeRequest)
        smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartfarming.WaterAndFertilizerServiceOuterClass.internal_static_smartfarming_FertilizeRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartfarming.WaterAndFertilizerServiceOuterClass.internal_static_smartfarming_FertilizeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest.class, smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest.Builder.class);
      }

      // Construct using smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        blockId_ = 0;

        fertilizerAmount_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartfarming.WaterAndFertilizerServiceOuterClass.internal_static_smartfarming_FertilizeRequest_descriptor;
      }

      @java.lang.Override
      public smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest getDefaultInstanceForType() {
        return smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest.getDefaultInstance();
      }

      @java.lang.Override
      public smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest build() {
        smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest buildPartial() {
        smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest result = new smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest(this);
        result.blockId_ = blockId_;
        result.fertilizerAmount_ = fertilizerAmount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest) {
          return mergeFrom((smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest other) {
        if (other == smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest.getDefaultInstance()) return this;
        if (other.getBlockId() != 0) {
          setBlockId(other.getBlockId());
        }
        if (other.getFertilizerAmount() != 0D) {
          setFertilizerAmount(other.getFertilizerAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int blockId_ ;
      /**
       * <pre>
       * Unique identifier for the block
       * </pre>
       *
       * <code>int32 blockId = 1;</code>
       */
      public int getBlockId() {
        return blockId_;
      }
      /**
       * <pre>
       * Unique identifier for the block
       * </pre>
       *
       * <code>int32 blockId = 1;</code>
       */
      public Builder setBlockId(int value) {
        
        blockId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Unique identifier for the block
       * </pre>
       *
       * <code>int32 blockId = 1;</code>
       */
      public Builder clearBlockId() {
        
        blockId_ = 0;
        onChanged();
        return this;
      }

      private double fertilizerAmount_ ;
      /**
       * <pre>
       * Amount of fertilizer to be applied
       * </pre>
       *
       * <code>double fertilizerAmount = 2;</code>
       */
      public double getFertilizerAmount() {
        return fertilizerAmount_;
      }
      /**
       * <pre>
       * Amount of fertilizer to be applied
       * </pre>
       *
       * <code>double fertilizerAmount = 2;</code>
       */
      public Builder setFertilizerAmount(double value) {
        
        fertilizerAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Amount of fertilizer to be applied
       * </pre>
       *
       * <code>double fertilizerAmount = 2;</code>
       */
      public Builder clearFertilizerAmount() {
        
        fertilizerAmount_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smartfarming.FertilizeRequest)
    }

    // @@protoc_insertion_point(class_scope:smartfarming.FertilizeRequest)
    private static final smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest();
    }

    public static smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FertilizeRequest>
        PARSER = new com.google.protobuf.AbstractParser<FertilizeRequest>() {
      @java.lang.Override
      public FertilizeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FertilizeRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FertilizeRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FertilizeRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smartfarming.WaterAndFertilizerServiceOuterClass.FertilizeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ActionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smartfarming.ActionResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Indicates if the action was successful or not
     * </pre>
     *
     * <code>bool success = 1;</code>
     */
    boolean getSuccess();

    /**
     * <pre>
     * Additional message providing details about the action
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * Additional message providing details about the action
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * Message for representing the response of an action
   * </pre>
   *
   * Protobuf type {@code smartfarming.ActionResponse}
   */
  public  static final class ActionResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smartfarming.ActionResponse)
      ActionResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ActionResponse.newBuilder() to construct.
    private ActionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ActionResponse() {
      success_ = false;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ActionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smartfarming.WaterAndFertilizerServiceOuterClass.internal_static_smartfarming_ActionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smartfarming.WaterAndFertilizerServiceOuterClass.internal_static_smartfarming_ActionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse.class, smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <pre>
     * Indicates if the action was successful or not
     * </pre>
     *
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * Additional message providing details about the action
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Additional message providing details about the action
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse)) {
        return super.equals(obj);
      }
      smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse other = (smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message for representing the response of an action
     * </pre>
     *
     * Protobuf type {@code smartfarming.ActionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smartfarming.ActionResponse)
        smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smartfarming.WaterAndFertilizerServiceOuterClass.internal_static_smartfarming_ActionResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smartfarming.WaterAndFertilizerServiceOuterClass.internal_static_smartfarming_ActionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse.class, smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse.Builder.class);
      }

      // Construct using smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = false;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smartfarming.WaterAndFertilizerServiceOuterClass.internal_static_smartfarming_ActionResponse_descriptor;
      }

      @java.lang.Override
      public smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse getDefaultInstanceForType() {
        return smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse.getDefaultInstance();
      }

      @java.lang.Override
      public smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse build() {
        smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse buildPartial() {
        smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse result = new smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse(this);
        result.success_ = success_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse) {
          return mergeFrom((smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse other) {
        if (other == smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <pre>
       * Indicates if the action was successful or not
       * </pre>
       *
       * <code>bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <pre>
       * Indicates if the action was successful or not
       * </pre>
       *
       * <code>bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Indicates if the action was successful or not
       * </pre>
       *
       * <code>bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * Additional message providing details about the action
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Additional message providing details about the action
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Additional message providing details about the action
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Additional message providing details about the action
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Additional message providing details about the action
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smartfarming.ActionResponse)
    }

    // @@protoc_insertion_point(class_scope:smartfarming.ActionResponse)
    private static final smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse();
    }

    public static smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ActionResponse>
        PARSER = new com.google.protobuf.AbstractParser<ActionResponse>() {
      @java.lang.Override
      public ActionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActionResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ActionResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ActionResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smartfarming.WaterAndFertilizerServiceOuterClass.ActionResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartfarming_WaterRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartfarming_WaterRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartfarming_FertilizeRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartfarming_FertilizeRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartfarming_ActionResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartfarming_ActionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037WaterAndFertilizerService.proto\022\014smart" +
      "farming\"5\n\014WaterRequest\022\017\n\007blockId\030\001 \001(\005" +
      "\022\024\n\014wateringTime\030\002 \001(\001\"=\n\020FertilizeReque" +
      "st\022\017\n\007blockId\030\001 \001(\005\022\030\n\020fertilizerAmount\030" +
      "\002 \001(\001\"2\n\016ActionResponse\022\017\n\007success\030\001 \001(\010" +
      "\022\017\n\007message\030\002 \001(\t2\307\002\n\031WaterAndFertilizer" +
      "Service\022D\n\010WaterAll\022\032.smartfarming.Water" +
      "Request\032\034.smartfarming.ActionResponse\022F\n" +
      "\nWaterBlock\022\032.smartfarming.WaterRequest\032" +
      "\034.smartfarming.ActionResponse\022L\n\014Fertili" +
      "zeAll\022\036.smartfarming.FertilizeRequest\032\034." +
      "smartfarming.ActionResponse\022N\n\016Fertilize" +
      "Block\022\036.smartfarming.FertilizeRequest\032\034." +
      "smartfarming.ActionResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartfarming_WaterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartfarming_WaterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartfarming_WaterRequest_descriptor,
        new java.lang.String[] { "BlockId", "WateringTime", });
    internal_static_smartfarming_FertilizeRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartfarming_FertilizeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartfarming_FertilizeRequest_descriptor,
        new java.lang.String[] { "BlockId", "FertilizerAmount", });
    internal_static_smartfarming_ActionResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartfarming_ActionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartfarming_ActionResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
